yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts.views import (add_comment, follow_index, group_posts, index,
                         post_create, post_detail, post_edit, profile,
                         profile_follow, profile_unfollow)

app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('group/<slug:slug>/', group_posts, name='group_list'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('create/', post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', post_edit, name='edit'),
    path('posts/<int:post_id>/comment/', add_comment, name='add_comment'),
    path('follow/', follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import CheckConstraint, F, Q, UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок',
        help_text='Укажите заголовок',
    )
    slug = models.SlugField(
        max_length=200, unique=True,
        verbose_name='ЧПУ',
        help_text='ЧеловекоПонятный УРЛ',
    )
    description = models.TextField(
        verbose_name='Опиcание',
        help_text='Введите описание'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    LEN_OF_POST: int = 15
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Укажите автора',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        db_index=True,
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:self.LEN_OF_POST]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст нового комментария',
    )
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        db_index=True,
    )

    class Meta:
        ordering = ('-created',)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        UniqueConstraint(fields=['user', 'author'], name='unique_follow')
        CheckConstraint(
            check=~Q(user=F('author')),
            name='not_follow_yourselfe'
        )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class BaseForm(forms.ModelForm):
    def __init__(self, *args, is_edit=False, **kwargs):
        super(). __init__(*args, **kwargs)
        self.is_edit = is_edit


class PostForm(BaseForm):
    def __init__(self, *args, is_edit=False, **kwargs):
        super(). __init__(*args, **kwargs)
        if is_edit:
            self.fields['text'].help_text = 'Текст редактируемого поста'

    class Meta():
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def get_page(page_number, post_list):
    paginator = Paginator(post_list, settings.COUNT_POST)
    return paginator.get_page(page_number)


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    text = 'Это главная страница проекта Yatube'
    posts = (
        Post.objects.select_related('author', 'group')
    )
    page_number = request.GET.get('page')
    page_obj = get_page(page_number, posts)
    context = {
        'title': title,
        'text': text,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    title = f'Записи сообщества {slug}'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_number = request.GET.get('page')
    page_obj = get_page(page_number, posts)
    context = {
        'title': title,
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    profile = get_object_or_404(User, username=username)
    post = profile.posts.select_related('group')
    page_number = request.GET.get('page')
    page_obj = get_page(page_number, post)
    following = (
        request.user.is_authenticated
        and profile.following.filter(user=request.user).exists()
    )
    context = {
        'profile': profile,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    detail = get_object_or_404(
        Post.objects.select_related('author', 'group'),
        id=post_id
    )
    comments = detail.comments.select_related('author')
    context = {
        'detail': detail,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post_edit = get_object_or_404(
        Post.objects.select_related('author', 'group'),
        id=post_id
    )
    if request.user != post_edit.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_edit,
        is_edit=True
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(
        author__following__user=request.user)
    page_number = request.GET.get('page')
    page_obj = get_page(page_number, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user_author = get_object_or_404(User, username=username)
    if user_author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=user_author
        )
    return redirect('posts:profile', user_author)


@login_required
def profile_unfollow(request, username):
    user_follower = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    user_follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if not is_edit %}
    Новый пост  
  {% else %}
    Редактировать пост
  {% endif %} 
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header"> 
        {% if not is_edit %}
          Новый пост  
        {% else %}
          Редактировать пост
        {% endif %}                   
      </div>
        <div class="card-body">        
          {% include 'includes/form.html' %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if not is_edit %}
                Добавить
              {% else %}
                Сохранить
              {% endif %}    
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Подписка на автора
{% endblock%}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock%}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p> {{ group.description|linebreaks }} <p>
    {% for post in page_obj %}
      {% include 'includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock%}
{% block content %}
{% load cache %}
{% cache 20 index_page page_obj.number%}
  <h1>{{ text }}</h1>
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endcache %} 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}
  Пост {{ detail.text|truncatechars:30 }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ detail.pub_date|date:'d E Y' }}
      </li>               
      <li class="list-group-item">
        Группа: {{ detail.group.title }}
        {% if detail.group and not group %}
          <a href="{% url 'posts:group_list' detail.group.slug %}">
          все записи группы
        {% endif %}
        </a>
      </li>            
      <li class="list-group-item">
        Автор: {{ detail.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  {{ detail.author.posts.count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' detail.author %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail detail.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ detail.text }}
    </p>
    {% if detail.author == request.user %}
    <a class="btn btn-primary" href="{% url 'posts:edit' detail.id %}">
      редактировать запись
    {% endif %}
    </a>
    {% include 'includes/comment.html' %}                
  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    Профайл пользователя {{ profile.get_full_name }}
{% endblock %}
{% block content %}
    <div class="mb-5">
        <h1>Все посты пользователя {{ profile.get_full_name }}</h1>
        <h3>Всего постов: {{ page_obj.paginator.count }} </h3>
        {% if user != profile and user.is_authenticated %}
            {% if following %}
                <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' profile.username %}" role="button"
                >
                Отписаться
                </a>
            {% else %}
                <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' profile.username %}" role="button"
                >
                    Подписаться
                </a>
            {% endif %}
        {% endif %}
    </div>
    {% for post in page_obj %}
        {% include 'includes/article.html' %}   
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}